export const TEMPLATES = [
  {
    id: 't1',
    name: 'Drink Water',
    emoji: '💧',
    color: '#3B82F6',
    category: 'health',
    difficulty: 'easy',
    tracking_type: 'boolean',
    frequency_type: 'daily',
  },
  {
    id: 't2',
    name: 'Read a Book',
    emoji: '📚',
    color: '#8B5CF6',
    category: 'learning',
    difficulty: 'medium',
    tracking_type: 'timer',
    target_value: 30,
    target_unit: 'minutes',
    frequency_type: 'daily',
  },
  {
    id: 't3',
    name: 'Workout',
    emoji: '💪',
    color: '#F43F5E',
    category: 'health',
    difficulty: 'hard',
    tracking_type: 'boolean',
    frequency_type: 'x_per_week',
    frequency_x: 4,
  },
  {
    id: 't4',
    name: 'Meditate',
    emoji: '🧘',
    color: '#10B981',
    category: 'mind',
    difficulty: 'medium',
    tracking_type: 'timer',
    target_value: 10,
    target_unit: 'minutes',
    frequency_type: 'daily',
  },
  {
    id: 't5',
    name: 'Call Family',
    emoji: '📞',
    color: '#EC4899',
    category: 'social',
    difficulty: 'easy',
    tracking_type: 'boolean',
    frequency_type: 'custom',
    frequency_days: [0, 6], // Weekends
  },
];
